apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eol-permissions
  namespace: argocd
spec:
  description: Project to backup uabierta databases
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  - namespace: virtuallabx
    server: 'https://146.83.63.40:6443'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'rbac.authorization.k8s.io'
    kind: '*'
  namespaceResourceWhitelist:
  - group: 'rbac.authorization.k8s.io'
    kind: 'Role'
  - group: 'rbac.authorization.k8s.io'
    kind: 'RoleBinding'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eol-permissions
  namespace: argocd
spec:
  destination:
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: '.'
    repoURL: 'git@github.com:eol-uchile/eol-permissions.git'
    targetRevision: HEAD
  project: eol-permissions
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eol-permissions-virtuallabx
  namespace: argocd
spec:
  destination:
    namespace: virtuallabx
    server: 'https://146.83.63.40:6443'
  source:
    path: '.'
    repoURL: 'git@github.com:eol-uchile/eol-permissions.git'
    targetRevision: HEAD
  project: eol-permissions
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false

