---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: eol-permissions
  namespace: argocd
spec:
  description: Project to manage EOL permissions
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "https://146.83.63.70:6443"
    - namespace: default
      server: "https://146.83.63.78:6443"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "rbac.authorization.k8s.io"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "rbac.authorization.k8s.io"
      kind: "Role"
    - group: "rbac.authorization.k8s.io"
      kind: "RoleBinding"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eol-permissions
  namespace: argocd
spec:
  destination:
    namespace: "default"
    server: "https://146.83.63.70:6443"
  source:
    path: "."
    repoURL: "git@github.com:eol-uchile/eol-permissions.git"
    targetRevision: main
  project: eol-permissions
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eol-permissions-openuchile
  namespace: argocd
spec:
  destination:
    namespace: default
    server: "https://146.83.63.78:6443"
  source:
    path: "."
    repoURL: "git@github.com:eol-uchile/eol-permissions.git"
    targetRevision: main
  project: eol-permissions
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
