apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: uabierta-backup
  namespace: argocd
spec:
  description: Project to backup uabierta databases
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: uabierta-backup
    server: https://kubernetes.default.svc
  - group: 'policy'
    kind: PodSecurityPolicy
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: Deployment
  - group: 'bitnami.com'
    kind: SealedSecret
  - group: 'batch'
    kind: CronJob
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uabierta-backup
  namespace: argocd
spec:
  destination:
    namespace: uabierta-backup
    server: 'https://kubernetes.default.svc'
  source:
    path: uabierta-backup
    repoURL: 'https://github.com/fdns/argocd-config'
    targetRevision: HEAD
  project: uabierta-backup
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false

