---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edx-uabierta
  namespace: argocd
spec:
  description: Project for applications in uabierta
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: edx-uabierta
      server: https://146.83.63.70:6443
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "*"
    - group: "networking.k8s.io"
      kind: "*"
    - group: "bitnami.com"
      kind: SealedSecret
    - group: "batch"
      kind: "*"
    - group: ""
      kind: "Service"
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: "Endpoints"
    - group: "autoscaling"
      kind: "HorizontalPodAutoscaler"
    - group: ""
      kind: "PersistentVolumeClaim"
    - group: "monitoring.coreos.com"
      kind: Probe
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edx-uabierta
  namespace: argocd
spec:
  destination:
    namespace: edx-uabierta
    server: "https://146.83.63.70:6443"
  source:
    path: uabierta
    repoURL: "https://github.com/eol-uchile/edx-kustomize"
    targetRevision: HEAD
  project: edx-uabierta
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
