apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: metabase
spec:
  encryptedData:
    auth: AgAWkZto6CJ+mC2nA9RJEzFCK5QYH2uzzXCPOmZev6q5KkqbP0qdN5PdQO4fAf9BX4UbdRdVxe99FSJstSr+OQgRir7rD8WnhxoK5/FX67qZKOSQIsFUYkwvL82BqZy0e8kg9ngU7mM8WJEYguvLuuy3dAo3yDQ1FNeo4ytOAfNFk+6VkvTYPVQkeQwNLgnYHaLDdnYvmq2NN1D8ZQeY6Ul4Uw0EouITzkAE2tC7bTANLm4jt2TD3IfGr+BiJBPju6YZwouJTGU0JcHRcMfCuly19FguYSNeJGtEs8vrscGIBkFZbAHCYs1+yTSyDq+BfVBHP8EjsHGlgp32gbF3NHsbqbRHOW6FjL3DaX8n/S/zz7IqrvosqhLqziFKKfWoSEpAJMgW4542OINsho1QZc3LE4Pon9rwb0moRIM45bD9CGloTMRyu0bWON1uKNAKkr7l/EoOH32pYJK4g35IeHF0eovz5s5e/C3FIJgfs++m/i46vjJx4RcLqxMdaQLXtNyxzkgTqfv4cwXAz6XC/nhiUTnPtdFdYuXYFBujvinjFoBIXXDj5xVQXl8UQnq97xMpz7u9Z8a34oJucquaxvpaOSeNb9BlsRnhpXuGvf4o0MCN7SYtHNvT3WUg1Nf7qI2VOCNI3d9+LWF6VUlzLGFwsQkEIVf9OgwheHQ7eXTF+/vTbvR7Y7SxNIDHBq2Zzut5ZjDn9OoKYiyyh9NOWY8c+3GXSW9Wjfmpe2xlpnZvr4siYgAXi3KvEJiSfxwPnPQFZqTZHyJ0+4Nvv2gOQbr0hgSN1dFT48tnmOqIEUd916c789dW28QygoTT6iHD9cudGpNANZsT54TG/bCfLxVLj/0sSZ00FqT0M6Oh6ThJ/sOgVPTCl7CGCCj7rzRb3qUM7VnrAw60Lzwc/PhQ1nmrW8sloReENPmrCMPGerN08myZYf/0ANmVgO5a39CqxsLzKBLRoF/2s3UGoogjZXrbmv0D8h2lrXxKQVvxndAmonsckrwOkSCtg56CQ6JM6tg=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: metabase

