---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: metabase
spec:
  encryptedData:
    .htpasswd: AgBlFqRwzRxkABttC/2y9p9Z12EDEqRu6dkzpu/AePM8RCRZrio9+bjX8yZypJAWONa0f/pi51fTpXwfvBcRC65VzCVvNULA0IVriLFMNrflDaKgXNltLvWS8oIEW8P5M4v3AqOAhMfcfdxkHDrdSHG4UtWpzPydxmnozMncZ9JNRgjNyqlAfSAzqYmHaaT7f9kmyrGWpEqwZQNREQb3CrG8l3fcLyUIApLC5vrlQQVSNyrdxF/IYOyTawD42nc4Txaje2jqU9gGdWsh2370PFhaZcuxiv1KuHygUbITgc+QI7cfCS/82Ob2y6EiozJlaVsuYPpSTBVFxJH+Mqh8c/ZR10tWug+8RNq/HEGs0C6x6RYIlyVpVYBPSl284YXUVGhkZQ6yf0u3u7W8rwa3Fc36dvYsMl4+Cc7euwoUqZQNcd352+XbdRwJ2em6+Eo9EZT7ZItRO9ul+mtW/5N5ETatuXM/OO0u8LaugIv21akahgPDR6tSLo4NPTzFEPJxfQ5J5HBfSZufzcaxVxVD/azoTEul6SJ6CSIz85wUVmRJD4VLvLSYarB6caOlrcTO2SzLzJL5mA6dV01LcZCJ9AceW4SbZx8MoKVwAopmcyt8dNlQ6HeP1hwQtJugs6mBnex34s09G0tMPagigd1drp/wBIJppEgQJmlz+9dPRQhRS8m6DclR9n7kywMzMSxFJBBOkpbVqQMClrE9bnfrMCUw9nTriGPjJy3oaBDgTZItcZ+k2YVVYt0izKP+Vg4O0rYMU/nHMLk+MApvw+hTWCDCf4EDwjhqr6HdCv6iy/CuMg==
    auth: AgBu1xEQZGv43nhHpgKpGww9MzJO9pHKWRlewlkZ7IznJpIPzk+aHlaLhN1kxyMlkQjSz4CDpZwg+l/PJ64Jl6/l09Nklwp+Yh3scbHXvA9Gc3kEKq2DITOe61w8hCEIbmZ11uUZj5i4wo347eopkH2DXHSSi2hnTRjj6O/E43V72cD+Z+uAyvO71stO2+VtVfbZl2bmSsun/yZDyegRCZ8kDeYEPgS2yyXm7KWS7dMg3LbhexVc+fiCAe+E9+ZfUajsrxGW8bOFBdtNaxidjuyEgbBwEfz9sa7hPN0IudMgzyXg76Yu+h8yk8ZQ4nCrqjhVRazqApltGxH19ei0Tb91+wCqfa5RTN9shOcBN1bbqoOp317clggzV0bLEJRi9rUMefOBC0sQJU4p+qTBarpxo8psRPhNWo8klO3jf0LCcSIl3bkpasHJJGfFf7b5YtP4w0/PpJzdTq3swi+COV7zf4Ahpd0QoIldv9Sg+l3ENThdzEZ/nPmmyBXhj3ii+S18wGK0U8ipQzw0YLXtn78psxutKYuaROPYpatQX9m4fkfsnsuVobmuo43g07FYKSDjAq69x3/0EZmjMmmTo/LVltOntiaH7b8vdBrI4nUGTZZ/tLafbLetm+qar6iq7PBYwvu31MR4uE4LpfqCUo4gIBQkAPpscosvB74DHIbAL1SRwt+CzhnVqifVzYUlT7WYGBZuZZQ/sLdFVZZbIH/DQFXOUryHL+zjrB1fMoEJV9Vpd7JZGUMMg3/X6hPNJEc0Umw6T+X4YHiEDOEARFlEkCEQ5tC5g6zHvopXmeQf5u1bfJvBVQFe9gVedGIlMq0Wy7DvGATWmsOjGd7vfbrIj0n/DB9Ga6xCLAjVthjwNXsTycSulw==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: metabase
