apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: metabase
spec:
  encryptedData:
    auth: AgCCgEQfqrNVv1SujwA5TqACqYnZtYUz0AjCvvAA1F6wWraxlEtNbxy1zUz3KFqr1tBi/gFsE8tgn/uLCfYNI9bafCRyCdx7Y18XoyA+f3SEWtBZASy50rO2YJuZxLN0b/r4EnVkkkI1B4UWnYh3zuAg4exuKMihfsiOqdVsCL6036GUHINAk6ny7269VKPol0JOnZLdPggUxdZKNSIp/oSeIetv9kmxRV28WG3VWR5Ge6ca7a4dkH+J8Gg5LiPBv6Nde39qn4/m1dagkHCW1OKh0w0oB0Ht1vjEvMXvqfm5XYvsuyanwz1LOlmYZle1kafaXdCgu+v+ra2fknei1qZ1OUBHpszspN//8PCjeZMKQI9lqKDKm/vOBG1GakV+kP2Ap+zhLx0g73uFMboECqI/x8U+y+4vDJxbxHZSFSc1bw+aa3nJte/y6RyhNKj8T+yTnKaCN4t2MnEEIvDUtYzivjGEH9ItfAKX4kRpVESGhlBOX2lzbr4szLbtRVXFsKBOi57Wivxb/gPRkUwXy5eyqRcP097Jb08sYVrMzNTA9nJad5w450I7yyxdfEUbw8dJeQDhXTzGRhKhgesBpWFEXapwuPiDoeouoG5+dXAqRwEeKuxRBDD4mm9jLPNAxJDS16O4rJMnWJYA2wg0rCbHiSiTT7xCxP4g9POwruGYIcpF9aOonb688+o5r1jFk6C/L3Via8retClr8GcnYxyPPT/+JYMuwS4osp6tPVQ4rmdoRmHcsB7SEPvUXRC3qa4DtNv3sJm5eiNNQ8xJPxah4fyuvXFGEIJZPwE3WRKC5vLLOEVwVa25KDzy9ZrIz2l6Fvrew+hHKckjDCQiUwOh4/yshhCGov82CVPyM4LlnPHD4F7ANiSHG26u4jilZy5g+olPkqKBzpo6uWnosaHiH/lxXucYQ86GFiosn43n2E8rIknoLmdC4HCWLkPnpgJRwQxe3n/diysBbvV98A0Ef2bIOVeXRDWTC26jVd8fHBCZvCxJFo9wjpU0bGY2y9TJzOa3pzPwUGr3Y7eYMJ8WIcyz5GT/LetNZsZJm+hMY3H26WI0hZb6F9qGopUbH5SUDQ9nJbb/yeA50BiDP+S4hwSRfz51VWCfWSCokeTJbaM=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: metabase

