---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: metabase
spec:
  encryptedData:
    .htpasswd: AgCr5yFXEjn8N+FdUsecMTf8mWYVfBLT0npyDhmZqcNx5jcjV53GSwwk+uCnOjp0E63s/Xq2cHdyl5Q1qub3VPKktsmNQpyLWUFxP/aS3y5uoUzcS9gQfomahSiSdop83SNfC1Z7+vgzMgFXV1+Lx9W1fdcmHEd9ef4/9tH30430er32dPe1kznRVeWXpWgKI4EbwBSl3arjS0bEC6CKHB+GstuOIX8T+z66HTDAgBhC0eq9r+2O21Ck3QznqQx4BVgkzC0/CQaTkUxrmv1s+rCW4TNZQ5vOBswpWDScrl5mvuNwxLvRiA4AMJw4H2CaGaq247ZW0DqpE6eODgUKbVeAwf7cXxl2ptXdx4uxJ/NTIqfcVB3XzmMpUvtI6Qh/rklzeD54U+yAay8/zMn2pygqht8OxYcd9Jabn/+OQZFPh5oHawYA74RlUu7qIRLS/bHv5sJQ83q4ywj+ICQpCYGsYZbYi0SXBFUU1LB8PXb37UzhSolxNJC5gLTvQ9++VA6PDeGO5PsugU0RX+Z3wCqrQi2798/uH8Uo/3oAI2rKncPXodKJulzhZnS4MsmYHeWIgQXZVcuO/J++z+O6JnRgEf5GUjFA7sYWabEGO/5zxkj2rrql8OSGq4xF4xCNHUEKOAzQu24eYCpoMrnnEqgnTIkU2r4ShpZKayxP8rv+33PyWr5enWRapeY64UGdFtXRJVs4XYuThE5KZtNu/233oPp0os/k/qyMGdOG1tU/ijulCRG6FlGEsmhuvAtPw7GDSYbMqEsKxN/oXTSPLLNCVQQDE0ZccTbSiViWimdFEPAuRzuTOHf17adx517eXjxqs+gABaVXBetQR56xw/9SN77rRj8IoY+LlG+f8CW4lNP79+1tD8FxLpF8yHTXyVfEIpe39D/1V0XXbeC1AewnsTJ3oYJlj4GuVO/48wODXDYWYUzBf9ztEG4rWkCor5HtKNXC1MLu+JIUXS1Jcsft0CI93/nYs+9TRgULl+V89caXMh94LHQh2+Wk9g4oRNCKrTkyeHjjA+y+jrud36Zq7fRNzQEz3HVevI0QLjPJF3Xbk3LCR7CWaG51U7qohbhqd8CCA1QYbv8xlDAskTYbGLSOaN9SIXR2SgpDoTqrk4U=
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: metabase
