---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: metabase
spec:
  encryptedData:
    .htpasswd: AgC96+5vu3wYw0F8qT7Ei7zjU5rZWzWe6UWpkzuIsMXP1eynOtK9QXa6n8qeYDzQx2BNQqtUoOAKlC22oIbWUz5Hq7+mLqxM53tF0KwEgudL4S7K3IRgytFAWYhQ3u8UWr5rj/ScmX71rFLupUqdqmX1M1WQTgzGeYWlRkxthDFJpLl80G2bY/BfE/gPscplBB4WX9JRJHRFdF6rQV3HiDX1mOZI40T4ide/OSN9LvatC7ioxjHGlnKyZBXRlh4GkcIBFpvreRcSRZzfMGggiTwvLsJUD2ja5iOEhf+NkCeTEZcp3od22/ufbRUgPoeVPRsiEWAszB7nmRDxO/AaHXxwvhCMwEx8px0CRcZH+mTr0Af5TJYcaB0GGeKXA/lO5Oc5rbGxoxHimGajz4TeORHtgu/qWpk3HQU3rYqO8MNdy8MWpLS+qYIGQsZ9YZ76Stw7NfF8BT1f6FzJC9zoKN1WiUaxYV0+M4AKqf4ORGxuMzy37CWg/0HXDl1Oy4kuQP66sI7NQUHOEUodBzVsAmOvifqPb9C+uTcLE+zwWxcGPczcCqaJF2V5boMzcxOF1e+6UYMEoW5dqcFPH3nQeDjdYXD2Cg2yOz8nhybrml7nlnBcRo9Rm70eD+3nDMY2K7VJAwuVr+7OdYcyNHkEWI5XUAhE4szNGweLKuZohPh6fD3xPv2CNJ7F6rzwmN4BBhNQ1+4BsH5PRBcF4ydkahyo3tkwENOs1QxhqdzZm7zahoR/hFyW5ikGSVzC86Nj0/mJIsti7uBlNuf3b4cbNbMrw0MqP7dLnoih2eh46sx1rw==
  template:
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: metabase
