apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: metabase-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-production
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: metabase-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  tls:
    - secretName: metabase-ingress-certificate
      hosts:
      - reporting.eol-ing.uchile.cl
  rules:
  - host: reporting.eol-ing.uchile.cl
    http:
      paths:
      - path: /
        backend:
          serviceName: metabase
          servicePort: 3000
