apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: metabase-auth
spec:
  encryptedData:
    auth: AgC1CxPEvrP/KedqQtIlVqtnYHBlz6dDDwwrASx+Ph/00KpFR8JNr5ziyRrBaeqmM64KXqDMEoscerbupbxDiQjj1FQxNkMtfzKlzb3lzFoiPhbBB6Cezg6UApMxAvoS9sMywijndpx0ZzGshXmqDNGnvfo7Hq0QQsoIHNBEeSNCZJMa6Ikkvvbayv8PlyypvMl6RmFMeykQ0CBDqxwCTqI/RTjjvhfiWNsbfXZxrfAIjFh23WsXm1zoqbAXO8NqLuR7Mt0VYyC2f7NJGqWvYWSy9VFQlyAtyUcsg3z7nxrAaJCifqBYatT4z9Kqck+6tsSZqhEdpxnNoYseYkagMTFifbvQz8IO5kI5as1MGs8h/0X2jLJMgixQ5Q3n1YHZ/Snc5baDnSl7umtyxa4crl+alQigs8j7b3dcVgrBiQcW4FyMpoTyxqGxb2o7HqxzKqPh2Olu5D49V8GVvQrLUgB6P6jBfITCs/FpYgvQLcTC57BWkCMth5ho3hLzuWfKWZhVU/f5z8afeFxaLL5uCwZI06MrzacsmjGWbw6PDgzv2/DHxfARAXucl28tYfaBNcJCwYwYaAYaO4Vcf287EtjKZr2g2XT98Ul2yEh51xZ4miHAPQd2gawLdzSLwYUHwgaWGeXpLrPXmdVb6WUESnFWL6Qgbb0dEANM5GQeNfP0aw/eFyAPrlUVy4bycK+YztMR/nARmazSL8+PCg+T5MTTImL67mzwSsI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: metabase-auth