apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-host-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - secretName: test-host-tls-secret
      hosts:
      - test.eol.uchile.cl
  rules:
  - host: test.eol.uchile.cl
    http:
      paths:
      - path: /
        backend:
          serviceName: test-host-svc
          servicePort: 80
