---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docs-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: docs-tls-secret
      hosts:
        - docs.oficinaeol.uchile.cl
  rules:
    - host: docs.oficinaeol.uchile.cl
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: docs-svc
                port:
                  number: 3000
