---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portal-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: portal-tls-secret
      hosts:
        - oficinaeol.uchile.cl
  rules:
    - host: oficinaeol.uchile.cl
      http:
        paths:
          - path: /
            backend:
              service:
                name: portal-svc
                port:
                  number: 3000
            pathType: ImplementationSpecific
