resources:
- portal-eol.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: portal
  newName: ghcr.io/eol-uchile/portal-eol
  newTag: 7a33c370f4d571e5d65b144b6c3ee62b6d54dbb3
