resources:
- portal-eol.yaml
- listenerset.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: portal
  newName: ghcr.io/eol-uchile/portal-eol
  newTag: 2bda269ed5aacb83e24f8b50160e124a39d21fc5
