resources:
- portal-eol.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: portal
  newName: ghcr.io/eol-uchile/portal-eol
  newTag: dca93e6d13509771f9606d11e2e6d2d177bd8715
