apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deploy
  labels:
    app: portal-deploy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-deploy
  template:
    metadata:
      labels:
        app: portal-deploy
    spec:
      containers:
      - name: portal
        image: portal
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 500Mi
            cpu: 400m
---
apiVersion: v1
kind: Service
metadata:
  name: portal-svc
spec:
  selector:
    app: portal-deploy
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
