---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pg-pass-file
  namespace: weblate
spec:
  encryptedData:
    postgres-password: AgCPPd18Xv60c3JNJJAly4rCrE7Yj++UrYMR7x5kvDWQxfKiIM6etdhGxjLhVcMUQz/nH2zsfsyrm4XBlM22KKcQ1ubGlwFKWey3KewEZ5xa9jI8H6137sbkUwDk5yX/2abR4O0qPAyinMPAUMC6FhOHb7/c2+G1i49AHRVHeYe9in3X64jWg4KJK/PU8LHvFptnf6Fe7PbFRxXbC/1DXSI3fD6IyxMyPhXd5ikLgywWKBZwo3SDl6xxZlzRngUR4vJs/Ocia4zlfRWFwMy6m8WGTU/mb3z9niKbjevG9kOFskgegAxGGMeT5yJdpebia4QsGEEnc5T/XLMcX+5mBAnSBpm184QArMHvfKmr8OIgT73pR5Xd6SRasFCiv2dHuQBtVqvMeUrgIlEauYptusxYQKVmPDa2MXvEQyOGLzgpf4OiabfsYGBdXoTfEEb2CENl+TGA3MhECQ38oKXVbvXoFPS2CzFO3cBCtl8Y6ygF/3eiBz3AXXF3Aejjnun0TqhCmnBkuTEz6cV8s2PcVr9ZXw+dT+X3pc/+YjuHNktP6YULSc7DmC2/81YITK/8l7SxfEDv3CuuZOShU5/wK3gyEzgzt/KhaK/7E603+UJOh8bFLJLHsF1wRGlSFqYNgsGQauiVCp64s34NUR5kJ3RXNmPtXiOPJGNX/hjIsAnjEpZLBhJObJbSM1P9uPoW/ZMaMF6G6WuOPKJhA1C2VWahymkor0GJld82
  template:
    metadata:
      creationTimestamp: null
      name: pg-pass-file
      namespace: weblate
