---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-pass-file
  namespace: weblate
spec:
  encryptedData:
    redis-password: AgCb50llcPrAX7Rdy28NZKAhogKx5DyzHOuXzfB+PtNo+OTJaOJcMza8FIDfiM45/ZjUxQeipCv2V3DFc4typfE5xAZHa85d8eTttbDnyd68vpcNSUv3niZYmTSbdkOxNFQktphC31AHJW/jISZIk3hR+sx8lGhOA/MazsDrmyacnsv8E4iwWp+iraIA10OvHssP51iwHYsrpCwVC0kFrXbxRpmLrfSrDeVXjNvxJ9PiJ3O985/hiMI6oaWxbleWZ9sAAQ/+x9xrVMQr7Q47et4hbxHGHyT+Fb/U6aYZ7fwa+HZOXwKPEM9NUz0oEr2fCXmlOM3bzT1p3UARULA1cXbFJiYWH+ych1A6pzEQdHSS5RuMP2uUGlIR1xRLwF61IbgfZTXfDESQXzzdn1wtyknHTRrklVE1YhJg7fciYC2Oy1whIYjaxPmC6rdN6DeFfMqvDUR3sOrm24Oa6+daEzxaXV2gwahB8/tgazl9+UQpYdeBP5+9c85crF0Mk8JPVH/OT3K2d4hbY9LEzOvoeJLCpFesEDtyA6ytmIaSEM0c8piBTiuhpWtze13SaKL53KLP4q3/RtwsfYpbYgmdKJsqNm3b6s98vVL9Ffe8g+IVN1S/Z6al9fdZEyaAlYKbur3JluYT3w0f6zXi7BLp0aAZZscR0KYK2bHVkW8E/hvc37MzHZAVdIVlNT+5hFg0xJET2IWO5Oz3gJGp6XpBdEzR8BG9401HywjI
  template:
    metadata:
      creationTimestamp: null
      name: redis-pass-file
      namespace: weblate
