---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test-host-eol
  namespace: argocd
spec:
  description: Project to hosting testing aplications
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - '*'
  # Only permit applications to deploy to the guestbook ns in the same cluster
  destinations:
    - namespace: test-eol
      server: https://146.83.63.70:6443
    - namespace: test-eol
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'bitnami.com'
      kind: SealedSecret
    - group: 'batch'
      kind: '*'
    - group: ''
      kind: 'Service'
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: 'Endpoints'
    - group: 'autoscaling'
      kind: 'HorizontalPodAutoscaler'
    - group: ''
      kind: 'PersistentVolumeClaim'
    - group: 'monitoring.coreos.com'
      kind: Probe
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-host-eol
  namespace: argocd
spec:
  destination:
    namespace: test-eol
    server: 'https://146.83.63.70:6443'
  source:
    path: test-host-eol
    repoURL: 'https://github.com/eol-uchile/argocd-config.git'
    targetRevision: main
  project: test-host-eol
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-host-eol-migration
  namespace: argocd
spec:
  destination:
    namespace: test-eol
    server: 'https://kubernetes.default.svc'
  source:
    path: test-host-eol
    repoURL: 'https://github.com/eol-uchile/argocd-config.git'
    targetRevision: oeol-apps-migration
  project: test-host-eol
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
