---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: moodle-ing
spec:
  encryptedData:
    redis.conf: AgC3EdLiMJvY83Dx4CxrbbN5IH3/or5vjAmUrpO6Zv4rDu6lOdbwOUVnkGBcwByX8trt63qOAenvNWVCc5Cdcb9bsPlMIHTLXP0V2c9XT9rMZhqnlWjSDazQ51vMsmFrK/jOhCAThjJtXygLb8uhrwzvqjNT45zhAU7hXebGIYBdxeOBe36M/exoUn64pDcNszG6Tww5YA7RfcrINMQCnmNbHYXb7WzUFGZGxG3WllH73Guj4roFh9N41fXsDNUowmMIuwiIBlrQNPPr9Y4cKFAXL8qEBCZtnzFoojySmASmxAkWh8uEPKeAdzmu9dPfAl4qPO9qUnsbFjJHfzjd17iH6NI2qsjnb5VwgfCYuM26ONTZcgR0ElhSwoFNtmPgfzn+yNWLchjE7P5WCbF1Ml4h05YbHOXtCF26LdbtVm0d+nP7uZMT/zJ0GGtiqIqDgEXnIVe+dcv9usv7Nrzij6OFNzAbhlYDOwQsw1Ayq1xPU3gV9hX1tSysntRDMYtGk01f94lVGiI7+cjxALxkk53QzyzmTU9IcLY5iGUeACNK/8f7O7TF9HyGshtjS0gy8FSH0HueMygqcXE1xGxZ7AJf76o9o3ZciONzTyKmLJ6dWcHHlyh7vSXOHPfn7Q6sq2qud8e5nUhEMnzMuyz9BMVvKIlh5Vj9ONaUNfHSYC1wvSISy8vrF79F4DjpswapnbljuWTuVFTm4GduLk78r5Aa0+YIUn1MpwpIkZbSZJ2YHh7RRUtECnoYyVtANNqzcALABbdsVNWrtfuhIuJ5bIcd4jjQvN1GHR58TQsWY3rH/QqvDtvmzvHo00Sq1Ath2eKtgsyNi5axsxU9Tpn/StR7wzaGi3R/DpDXcj3qI9pYJY9g7/bLYblE5iSqoaPrE5KiQo35mQTo3NnF8syctp9FPcBTqewAZAmhtDzoqOfF12BLMptsDTa74ipml41wrH8rrgPpGpBcBSDXpnDiBM/dH0Ida3GL4NqGXo9voxpUALlZIcDS8mZFqxyV6q66PBPHTeq7qMHjG/RfDOEW/FXzJfqQEBDnm1sZJBJbz5wvQSeiIKtaZAWnZohNYUEpuPgMnjLPAnvK/BvVDI1K0UWudTWFVFlEZStUyXApmSBKMDn6uJP4MLwIjNrkyP9BBqmSA4sRISD1WLo9o+gtvvHzneSxV3M9O3jILwf6FbsGKPeRsAj/y3U7AXQOYjEUgfs+OG/1RTsQRfQr6PvYptsaojIrz4AqV6EMTMrzstRQH2UUlpeiMve8qdLPWuUTkh9fVuYiONtj9RK+dITUxzHnkhlO9hag+afdwHDpKfhX6a+nNGcv/DmVs0CZCVTiICrrP5d4aeZXD882Xu2p+YFxlVyisrEv78CKbdL2RzBL9EAYtr/Tdt8TrjZnBN4Sl0cVXLVUataDDIhvFtihzQPkCxY88tlRUZLLKkiqt2ZZdsUb2394cigR9OC+ySRHrowDtj0rGIP7QvIKEahrrnnqhzUEMZhk9Hc7T+fVNP6K2eaBOtQzFMTTzWp2nTHevnnqblqYhz3Ur/0cU6eAQRyKpyGZk/I5xHQJzLhSyMsjiHsEwStVBdWOQoaPWAVhQwcqxempx8W22w==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: moodle-ing
