apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes-charts.storage.googleapis.com/'
    targetRevision: 5.5.5
    chart: grafana
    helm:
      parameters:
        - name: persistence.enabled
          value: true
        - name: persistence.storageClassName
          value: local-path
        - name: persistence.type
          value: statefulset
  project: monitoring
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
