apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Project to backup uabierta databases
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-repo
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: monitoring
    repoURL: 'https://github.com/fdns/argocd-config'
    targetRevision: HEAD
  project: monitoring
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-kube-prometheus
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/eol-uchile/kube-prometheus'
    targetRevision: eol
  project: monitoring
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
  # This solves a bug where argo-cd will mark the application as healthy but OutOfSync
  # this occurs because kube-prometheus updates the status field in the CRD. This field 
  # makes argo-cd diff's think it is out of sync.
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: probes.monitoring.coreos.com
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: prometheusrules.monitoring.coreos.com
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
      jsonPointers:
      - /status
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com
      jsonPointers:
      - /status
