{{- $fullName := include "projects.fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-argocd
  labels:
    {{- include "projects.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterissuer }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
      - argocd.staging.eol.espinoza.dev
      secretName: argocd-ingress-cert
  rules:
    - host: argocd.staging.eol.espinoza.dev
      http:
        paths:
        - path: /
          backend:
            serviceName: argocd-server
            servicePort: https
