apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minetest-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  resources:
    requests:
      storage: 3Gi
