---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: moodle-ing
spec:
  encryptedData:
    redis.conf: AgAJlE6grCJeQ6TT0axpw4Yi5cjHVLlXl6kir1ZtTvZH6vLYItTaFYfJ6PiurNRWwQ+JVZezjDFgIAgEj+DHlK9a3EfadzZ9pdzUkhIGYK22xnZrXf0lZRTOXe6PG1rrRwI6/ZVUISEeh5CcBWWYRm4rO+WQC3K5AuVRxTU9OS9VruQS2rzcehaIjtxzaY4Zx2619YltNAQ4QZvFAdKuWZ+y7pM4NeWf4nLRGRaZoVai05yX5wyltD4q+BiA+E7yo2VxZIVRNRg+3A9Y+8EJA+rW+RDdhymL9nl/ln+X2//FSm7BgvrqOSjhyMgMUg8lSjh6ot5qkXFqfhRu5zegrVU0BWUi3PArJGnlx5sA91sgOPw5OlGR26JV2TgpQeNgxZLAKnhWVnkDzMTMNEjFlvvoMg37bO2trAInbjCRGOmntSN1ZnVUL6AG9ztWSnfQZFJRPSaoudOsHVtwRK31YpDV0Zz+X+omyJOY6lXycRgeRdAu+8OY6LzdF7WvCnOMcw0b4PPIzfni9NkldnURnxlP/neM/K55Y1TzX2gajw+QoCaZQcVEAe6QCxIlvO0Hv6x/DXtkujKIv3KuYYWqfbInU1S7CmL/F9nPD8AnmLpu4lL782rvfeBQein4lG6jdhKnN9wDYg/xrN6c/WEcfJ6/Jp2ePyemG4UwnUe3Rri4VvjSUjkXNrihbx9eOnlkPFg3vPTEs95mx0zQArLrycii3J9kxHAr+jVDULc+rsb5aWr+hTW4kRFjpqezcF2kvR79tkBh3jQD8hqX7z8xdp9KSCS++SX15oxBjzPyupgjWsx+vIlEVwseta3tU1z7pF6OeL5I/PYe+Fv3nuFMCfsnpgByFNRjRLQ/D44Lm7wyqR/8Bwoe8z+wVXKx0jjk6JsO9zcHiBz63M89Lz3pa8A359PucrW5WEdqxTsLfb+GoFISQnb7kVkMtokOQd3+Lk88fNBMMKua8/+939tebflQvn2nZ84dK5beuUkhyag4+RB9bORMMlJeWDkRAKOD9bEtfDmLSJEpOt/Nzghx4JVmxwcd2jgbvDv0aQzrjYIvzQ5D6NJSdBndZnYforTwuj/VtDRigvjh/3Ia6HMguG6gxUlarZ5v+Dy4ZGPUMb8DK66Jihe+YIaDEuvAUzFOFWdWBXlCY6Y3DSb8wuImwsV1Iq8eNU9hXqqNJWC7ttS921B5ueTkp01bvn5UcIVo0IWUntg/mwiGqle64RW6bxQ/cf9asEnq0nUU7PRhKOdsRUogsYlApDsBO1QBJYWgaNUVleIXaT3fqOSwQzhocEacvpS17kv4OEe7eFP6dycMXctfjCmmCG9TwVgIvU5ZKcbl7C4l35h01J2yGTQue/eixBLFV0AoOOUSqzftu9M4cIUx0si2UNXrAAyP+rE9hHQGpZ7inJf6XKDnrAyL2NC24vfQVte2h6qo00FFyDtvIYKysUAY2SGh/IncTv7/0oZpw0+OgjpMXNcpfM/oHESV4p0cVdn/4sRvX9ufhAPNeUzPjNywOx14sYnKAgxgfFawBSZkDo15ZNGgXYMhNd6rJawvVUJZIQyGZylSx0P0rv2MrYdN/aC6+hVLPdS/0pF2pK71JCdmcw==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: moodle-ing
