---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: moodle-ing
spec:
  encryptedData:
    redis.conf: AgCrPrNjE47cEN1ZtbmJOf9JG6BzoCZKFgd1bGZ4soYDFRm8ncJ4Ce0Z1nBguUND3raDnOYpSSsBuh5TvAQErICg9ZpUyVUSp/R+uY0g2Vs88RFeaS6SEksZOEyCLNhAUDuKOwy5IJy0+S3uhHF7j8gdGCruBd7Bje3YBg1P/BnZjiaDLS4PDJQTTJJ14ac+1rQP+Q0wcQS/e8dmoTlGmZU+NIDIWzwag5jHt2XQtcHgeNHucXrtuACr4X4gNCFXATyaZO+vqjVeb+8jm65zc+x+2bjZJeTOaQwdNGo8anvbgJMftn+QdzqDxAJnxSzlmfQT1QFZdwMfpi2k8feXGVEQwFbXm1Z+PfM72Jkdv6wi0Ocb4O0ubR0og1CmWopwZFHlsXh41Afo8Zo82bakBhHiJhxnAVhBmRNUkKAtQArE+3tk96Hu/2kslW8Ey15mHbzEQDKYjhI7t0zn6h1WK1c0NhMyH3P+JIHoJP2/kgyL8u2Kcb6gd7XJSj0l7Febimhe+C0L+LLf5rsgeBBF1Wg0B9yBrXYB/NcF8LpmqJt4x8P4LxrWBUHEt+C/8TzvlPKITPgVAy2uyVZkYr63lGscfxA+ZLjwKUMjhbpmrpnZEM0CaGHb3NBft9f3vAv441Z6/NpVdOhdRX0Gyb23pZHuoHvaygU1gWUGYipVKOi38az+qFM9G2WQ25d1gOwwtCEj2wOYKbwXNymN+LlQo03IJ1TQnDjLbDjvkpFXrkaucZ2/lGvcUwcto27hrBPlwVbI6tecYhzAb3J2Y+BWHWsXUUHKDsEpsjnaehso/HgQuDU4cGUOovnbupT2ucIc7EIlG+wmAL2Zw0o7jp4oqGyRFkEJe1b09D28sKQAhZDdH5XfhfhT/J64u34WIM8FUHiCj2Pub3rXnDXwCpplNI1MGzFoMm8IUUEyo+pSDeiJ7PWkjvWoKymSHvG9MPzOkdqRPXRMIn+FhNEgAnttsFPIbZhn9RjoO79aH2/tFFa8r3hlHH7wuxrlO0GEIUJFjQs6hc87vaj2LHhIF93L1hxhTpUjFa51RYm+3d/neU/d9GFPATqmwpbtNZYMlbCbRxspsqbzYnzSda6PkuOaWN8K4cQvOBQQX4JF0C0hFcKRhkESEo1T+Y6u2SJFVNWuNgzSDRGIMaSTKuy+ZaWHiX/sOF+d7YHOsPZ3ubCOXebQ1SmLJizAK7PRkgbvHd7uldQETfa0WmRjUUCGH5h9rc+1QY47OSHk+h4IXWDKAWx8D13Nu2hXt/1+DdnMV+WhSYP8whK8HtE7aO14Rk2BtjwqdKN+OiZXCla14WXLvsb/IHcR3jRSWoP6ynPv2DxSAD6q4DHS5m3h1u7SM8IacLxc2tKTAJmgMAvI+3xAHuDVi/GGAJHfmOjH01s5RO0FYP/YH6RN+ld5MzUPEcNbYDTx2K0/SE8pP5Y27OR5wSFxghVV3Dkt3ApwGcL9pQqf3qSnhmB/UkRQW9OE3VdqHa4SCteyIyLJxyAJtRc99UqwYIUuyKCz3lkQiucwiyqvuE9r5rYj9WzGCLcoj3C665mV3f00z0c4fzNVd5xYwFb3Bha3kR8KK0zNFpO+nHjV3mC1bUz6T563PQ==
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: moodle-ing
