apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minetest
  namespace: argocd
spec:
  description: Project for minetest
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: minetest
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: 'Deployment'
  - group: ''
    kind: 'Service'
  - group: ''
    kind: 'PersistentVolumeClaim'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minetest
  namespace: argocd
spec:
  destination:
    namespace: minetest
    server: 'https://kubernetes.default.svc'
  source:
    path: minetest
    repoURL: 'https://github.com/eol-uchile/argocd-config'
    targetRevision: HEAD
  project: minetest
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  syncPolicy:
    syncOptions:
    - CreateNamespace=true