---
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
  - umce.yaml
  - secrets/common.yaml
  - secrets/umce.yaml
images:
  - name: backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: 4bf086f56775d73184ce4ca31e1bcebc4f772c9f
