---
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
  - redfid.yaml
  - umce.yaml
  - eol.yaml
  - openuchile.yaml
  - virtuallabx.yaml
  - secrets/common.yaml
  - secrets/redfid.yaml
  - secrets/umce.yaml
  - secrets/eol.yaml
  - secrets/openuchile.yaml
  - secrets/virtuallabx.yaml
images:
  - name: backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: e7d191eeb61f0c10e93f50ec07f9a16defbb5b81
  - name: old-backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: b8f3899351938d6ae3a12cfd0700e3ce575308b8
