---
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
  - eol.yaml
  - openuchile.yaml
  - redfid.yaml
  - umce.yaml
  - virtuallabx.yaml
  - secrets/common.yaml
  - secrets/eol.yaml
  - secrets/openuchile.yaml
  - secrets/redfid.yaml
  - secrets/umce.yaml
  - secrets/virtuallabx.yaml
images:
  - name: backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: 4bf086f56775d73184ce4ca31e1bcebc4f772c9f
  - name: old-backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: 229c53b6872546ab2ab84ab8cb01f431a0cdb53c # temp testing image
