---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: virtuallabx-backup-daily
spec:
  schedule: 0 5 * * *
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: edx-backup
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: cleanup-pvc
              image: busybox:1.36
              command: ["sh", "-c", "rm -rf /host_mount/* /host_mount/.[!.]* 2>/dev/null; echo 'PVC cleanup done'"]
              volumeMounts:
                - name: virtuallabx-bkp
                  mountPath: /host_mount
          containers:
            - name: edx-backup
              image: old-backup-container
              args:
                - /root/scripts/backup.sh
                - daily-test
                - minio,mongodb_comments,mongodb,mysql
                - keep
              envFrom:
                - secretRef:
                    name: common-config
                - secretRef:
                    name: virtuallabx-config
              resources:
                requests:
                  memory: 256Mi
                  cpu: 750m
                limits:
                  memory: 2Gi
                  cpu: 750m
              volumeMounts:
                - name: virtuallabx-bkp
                  mountPath: /host_mount
          volumes:
            - name: virtuallabx-bkp
              persistentVolumeClaim:
                claimName: virtuallabx-bkp-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: virtuallabx-bkp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 200Gi
