---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: znuny
  namespace: argocd
spec:
  description: EOL help desk implemented with Znuny
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  destinations:
    - namespace: znuny
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "*"
    - group: "networking.k8s.io"
      kind: "*"
    - group: "bitnami.com"
      kind: SealedSecret
    - group: "batch"
      kind: "*"
    - group: ""
      kind: "Service"
    - group: ""
      kind: "Endpoints"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: znuny
  namespace: argocd
spec:
  destination:
    namespace: znuny
    server: 'https://kubernetes.default.svc'
  source:
    path: znuny
    repoURL: "https://github.com/eol-uchile/argocd-config"
    targetRevision: main
  project: znuny
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
