apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edx-dgd
  namespace: argocd
spec:
  description: Project to backup uabierta databases
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: edx-dgd
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  - group: 'bitnami.com'
    kind: SealedSecret
  - group: 'batch'
    kind: '*'
  - group: ''
    kind: 'Service'
  - group: ''
    kind: 'Endpoints'
  - group: 'autoscaling'
    kind: 'HorizontalPodAutoscaler'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edx-dgd
  namespace: argocd
spec:
  destination:
    namespace: edx-dgd
    server: 'https://kubernetes.default.svc'
  source:
    path: dgd
    repoURL: 'git@github.com:eol-uchile/edx-kustomize.git'
    targetRevision: HEAD
  project: edx-dgd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
