kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: virtual-labx-blackbox-monitoring
  namespace: monitoring
spec:
  interval: 90s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - https://preview.cajalosandes.virtual-labx.cl/heartbeat
      - https://studio.cajalosandes.virtual-labx.cl/heartbeat
      - https://cajalosandes.virtual-labx.cl/heartbeat
      - https://norteamericano.virtual-labx.cl/heartbeat
---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: open-uchile-blackbox-monitoring
  namespace: monitoring
spec:
  interval: 90s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - https://open.andhael.cl/heartbeat
      - https://studio.open.andhael.cl/heartbeat
      - https://preview.open.andhael.cl/heartbeat
---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: aulavirtual-blackbox-monitoring
  namespace: monitoring
spec:
  interval: 60s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
  targets:
    staticConfig:
      static:
      - https://aulavirtual.institutonacional.cl/
