---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgBj4WEOWQEVOiBPEl0wdJ2BBw+ovXEY9ZtdkujVhg3yHUWu93d6eWRlwjO6D0kyaX2l5Sbg8pq6vRrq/52L/yUCx/n6S4XBUxalCSeOplxLky0GXFjdlEkFdlGRus0o62TljC7tRRd9vBrIjQBcwceG5aZkJXtLK2cD7qFfY0OtrqA1DLg5XwmVHC41PH/KehuM/e67C4qLovwMPSDradWgf4mhcZDg+tfOBVQtdAyMU4lXB1zC9Q5XQhtlAL+p350QSsr2J752AB5+SE/hyTo1qAY4u/OrQgdttl327sSKqdpNo3s8KhsjDd6r/K0pGwUQhml7bwwz8Bked5MQFDd/m+RjQmyFCuoMbeByViJVvQcwvaCIxImLc30A8xTOQYSjTE20qNI4YTro3FARFfobSlU4KyUUok1L6LNlfA6lggJ6ZPX25ZxeNr+mdXnankWbTnQ485WiLab1uOh7NcgtoPnVsuvolTMBsM0OmV88vGlKX1ToI6wd2Fsy13E4Df+DfNIrcSasq7DfI8BGkxiZPbS5//ZzpN798iHDWdxiE53N2D94fJmikD3LFWFYzQpjEsEsXlKY4Izo9UvggKiNUoprpbWf48uIp9rOb9fBWXmbcwqSs5eHn9wcyJVHIULGj1MyQtIvOwxqhHmSRoKwGw3PpL2lbhDNfuyKVUZx/Da1BCrMSbjSrbXpcDYOax0jv7efnnR5yVcJoRDbElzGiuFOPIu0ixy5Z7yrHXbJq1hdCa2pbz/giKZKrdDqM9Bhm10XsT4tlYvPpKN6yYBf5CcKlwvZx8c7VV25sXyq1Qse7vPKXk2JvmO5KGBfwL2mmImzCcRlEDb4vkQ2CFY0tJe8nbQQtA4=
  template:
    metadata:
      creationTimestamp: null
      name: discord
      namespace: monitoring
