---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # Authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - monitoring.eol-ing.uchile.cl
      secretName: argocd-ingress-cert
  rules:
    - host: monitoring.eol-ing.uchile.cl
      http:
        paths:
          - path: /
            backend:
              service:
                name: grafana
                port:
                  number: 3000
            pathType: ImplementationSpecific
