apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
    # Authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  tls:
    - hosts:
      - grafana.staging.eol.espinoza.dev
      secretName: argocd-ingress-cert
  rules:
    - host: grafana.staging.eol.espinoza.dev
      http:
        paths:
        - path: /
          backend:
            serviceName: grafana
            servicePort: http
