---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: psp-permissive-node-exporter
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-permissive
subjects:
  - kind: ServiceAccount
    name: node-exporter
    namespace: monitoring
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: monitoring
