---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: basic-auth
spec:
  encryptedData:
    auth: AgB3R0TDHZSPFTYy0hULA8JwQNTsd7RGD2MlnV0AFga0BsbdBCKIIaUVFe9cMQUg/aYZsL4X9lLpLYff5/O7tHjQ72OqkRYziZkjzbwg1Ux1UeMkeLM4DNO7090sm6rNO3PgutlB1pXqBwwXltbaSzuB1Vkhvq3RyggTHdU0Zuy9486HZwM+3wXbQyJ9LdI1FDFpM/qbAf/pf9rtRmJIzb+x6BQDvBU5Om5OJkkztxG6Am0Evk5zUiYQctKwi5m8BWkikN6OeXDnyEItspPAlFaayHPswWCSBhjHk0MPOgknOmfsKhSnzQ0OVOTIW5oEr+P/PfnPrmOHptkjQxMapnHEMGyvcokztSytGy9k4Dq33gAvE3uXDDtAsFkWCGCcBTi99XoN9J+dfnC2pcrHacqFvdtvB2XK3NUwMgu0WZ90Xu4ZuxhLyOFv+TsJ82ESdjnT3SDqUDKvuFf8PIw6z1NhwXG+9QH4KfsoHx1FuaC08WklubJNXd8bmsfglN4qJFz9fBFz0yUWK0mE6ef3NxGuek5a5kMyBBh8M47O4PexijR94T3fZFwm8to5bSm7FMrCGYD8GiQDqhTt1LZ5RvYnHh59rej7Mb8SBzIQp8Gq9ormCxfoY9zr9kbpV3VmZgnU3i/JbIn1CVjdFyZ2incxf1K2O9lTzc8TgXTr1x52g5vDapwl+bjzkbPSIf/SnZTl2nLBB/eG9kKYnAWSQlLJwjpupFpmeJZVZdSnQtjGIcdK8FDO3uYfvCwQdackWMgtZIQIUSdgZNmZXCImxHmMjg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: basic-auth
