apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: basic-auth
  namespace: monitoring
spec:
  encryptedData:
    auth: AgAaqLHnyMi9GUdm9h3P8sP+evROAzsJIxUrkl/s2lAnwTqSndE3hFXQvwdDWiZeXFZLvl6pgPdk2JiYvGULiBafpmu8LLuJgawtzYET6Rxm5jrSLI6IK5ZZQRMN5q5PqEHWxNohKhQkn3wdWCODGYfMiZyLOFv9YSjXAhpPt6vM/ymG83pFCJ6nLbD+iRr6gn+R2xM1o+u3eXGprbqEqMYpuijn97D8agbRRiFFzBIr3G3amqKGPUjz+h3KjtTY/MdVB3ebt+zyahZT4W01/E7N8G/XMMOoRqZeo2HcUrxfDfxKGW8gEqBZm8/rpaBsPK6EHr5hHEQFFiv6t0SuQvefapODXg3Sbqr17IyIPKb7TtHBo8iyQBt+hEygSlWrDv5nl6OKbFFzZStkW4Nbg8TabpeKW/cYBO99ZgdzrOld6THaSM/WWjbLddDYkQhIR0/iWzz6BA2q2fPib9PIWHbNLicPsXGww0NBVHSGgqB/dxPkj1ABNa+WhE0xmOQWfTYbYc3sJlQ5U6wMsa9CSbzTEIB/CAohjLLo/nSQuMF6iaRn1kn6C+b/2mZrxQwEtLrY3FCvcuCvzr63a7OAk4RAUAupRUrCJNPUTyjMhtY34sKxFEB97MoK6NCgWYR37rYbKMQf17X6RV7ZWV9exYWrKP4owwXN1Mh9lqygqCx8BDO1t9/dk0Ehw11dPU+yeuh4JgwbGzFZpr5rO4RiEt0Zzjg2icJyg32uRZI+03ZWf1F/Pu8mRjokd27avgdpw6lnSQKqL1lUjc5EqSruWS0xbNQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: basic-auth
      namespace: argocd

