---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emi-wordpress-nginx
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emi-wordpress-nginx
  template:
    metadata:
      labels:
        app: emi-wordpress-nginx
    spec:
      containers:
        - name: emi-wordpress-nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-emi-content-volume
              readOnly: false
              mountPath: /var/www/html/
            - name: config
              mountPath: /etc/nginx/conf.d/wordpress.conf
              subPath: wordpress.conf
              readOnly: false
      volumes:
        - name: wordpress-emi-content-volume
          persistentVolumeClaim:
            claimName: wordpress-emi-content-volume
        - name: config
          configMap:
            name: emi-wordpress-nginx-config
      terminationGracePeriodSeconds: 45
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: emi-wordpress-nginx-config
data:
  wordpress.conf: |
    server {
        listen 80 default_server;
        server_name _;
        client_max_body_size 300M;
        index index.php;
        root /var/www/html;

        location ~ [^/]\.php(/|$) {
            root /var/www/html;
            include fastcgi_params;
            fastcgi_split_path_info ^(.+?\.php)(/.*)$;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass emi-wordpress-fpm-svc:9000;
        }

        location ~ .+\.(js|map|mustache|css|ico|gif|jpg|png|svg|ttf|woff2?|feature|html|txt|xml)$ {
            root /var/www/html;
        }

        location ^~ /blogs.dir {
            internal;
            alias /var/www/html/wp-content/blogs.dir;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: emi-wordpress-nginx-svc
  labels:
    app: emi-wordpress-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: emi-wordpress-nginx
