apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: static-sites
  namespace: argocd
spec:
  description: Project to backup uabierta databases
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: static-sites
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  - group: 'bitnami.com'
    kind: SealedSecret
  - group: 'batch'
    kind: '*'
  - group: ''
    kind: 'Service'
  - group: 'monitoring.coreos.com'
    kind: Probe
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: static-sites
  namespace: argocd
spec:
  destination:
    namespace: static-sites
    server: 'https://kubernetes.default.svc'
  source:
    path: static-sites
    repoURL: 'https://github.com/eol-uchile/argocd-config'
    targetRevision: HEAD
  project: static-sites
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
