---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblate-filesystem
  namespace: weblate
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: "longhorn"
  resources:
    requests:
      storage: "2Gi"
