---
# Source: weblate/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: weblate
  namespace: weblate
  labels:
    app.kubernetes.io/name: weblate
    app.kubernetes.io/instance: weblate
    app.kubernetes.io/version: "5.14.3.0"
