---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter-eol
  namespace: monitoring
  labels:
    name: mysqld-exporter-eol
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9104
      targetPort: 27524
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysqld-exporter-eol
  namespace: monitoring
subsets:
  - addresses:
      - ip: 146.83.63.76
    ports:
      - port: 27524
        name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysqld-exporter-eol
  namespace: monitoring
  labels:
    name: mysqld-exporter-eol
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      name: mysqld-exporter-eol
  endpoints:
    - port: metrics
      interval: 30s
