apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edx-virtuallabx
  namespace: argocd
spec:
  description: Project for applications in virtuallabx
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'git@github.com:eol-virtuallabx/edx-argocd.git'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: virtuallabx
    server: 'https://146.83.63.78:6443'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  - group: 'bitnami.com'
    kind: SealedSecret
  - group: 'batch'
    kind: '*'
  - group: ''
    kind: 'Service'
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: 'Endpoints'
  - group: 'autoscaling'
    kind: 'HorizontalPodAutoscaler'
  - group: ''
    kind: 'PersistentVolumeClaim'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edx-virtuallabx
  namespace: argocd
spec:
  destination:
    namespace: virtuallabx
    server: 'https://146.83.63.78:6443'
  source:
    path: edx-virtuallabx
    repoURL: 'git@github.com:eol-virtuallabx/edx-argocd.git'
    targetRevision: HEAD
  project: edx-virtuallabx
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas