apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: graylog
  namespace: argocd
spec:
  description: Project to backup uabierta databases
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: graylog
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: 'policy'
    kind: PodSecurityPolicy
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  - group: ''
    kind: 'Service'
  - group: 'bitnami.com'
    kind: SealedSecret
  - group: ""
    kind: PersistentVolumeClaim
  - group: ""
    kind: ConfigMap
  - group: rbac.authorization.k8s.io
    kind: Role
  - group: rbac.authorization.k8s.io
    kind: RoleBinding
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graylog
  namespace: argocd
spec:
  destination:
    namespace: graylog
    server: 'https://kubernetes.default.svc'
  source:
    path: graylog
    repoURL: 'https://github.com/fdns/argocd-config'
    targetRevision: HEAD
  project: graylog
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false

