apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-uabierta
  namespace: monitoring
  labels:
    name: redis-exporter-uabierta
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9121
      targetPort: 27425
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-exporter-uabierta
  namespace: monitoring
subsets:
 - addresses:
   - ip: 146.83.63.75
   ports:
   - port: 27425
     name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-uabierta
  namespace: monitoring
  labels:
    name: redis-exporter-uabierta
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      name: redis-exporter-uabierta
  endpoints:
  - port: metrics
    interval: 30s