apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
spec:
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/base
    repoURL: 'https://github.com/kubernetes-sigs/metrics-server'
    targetRevision: 6d92704c5a68cd29a7a81bce68e6c2230c7a6912
  project: metrics-server
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
