apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metrics-server
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: metrics-server
  destinations:
  - namespace: kube-system
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
