---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: portal-eol
  namespace: argocd
spec:
  description: Project for portal EOL website
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: portal-eol
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "*"
    - group: "networking.k8s.io"
      kind: "*"
    - group: "bitnami.com"
      kind: SealedSecret
    - group: "batch"
      kind: "*"
    - group: ""
      kind: "Service"
    - group: "monitoring.coreos.com"
      kind: Probe
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portal-eol
  namespace: argocd
spec:
  destination:
    namespace: portal-eol
    server: 'https://kubernetes.default.svc'
  source:
    path: portal-eol
    repoURL: "https://github.com/eol-uchile/argocd-config"
    targetRevision: main
  project: portal-eol
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
