---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graylog-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: "nginx"
  tls:
    - secretName: graylog-ingress-certificate
      hosts:
        - logmonitoring.eol-ing.uchile.cl
  rules:
    - host: logmonitoring.eol-ing.uchile.cl
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: graylog4
                port:
                  number: 9000
