---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./es6.yaml
  - ./graylog.yaml
  - ./ingress.yaml
  - ./mongo.yaml
  - vector.yaml
  - psp.yaml
  - secrets/graylog-ca.yaml
  - secrets/graylog.yaml
  - secrets/vector-cert.yaml
namespace: graylog
