---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: 5policy-vector
  namespace: graylog
spec:
  privileged: true
  hostNetwork: false
  hostPorts: []
  allowPrivilegeEscalation: true
  defaultAllowPrivilegeEscalation: false
  hostPID: false
  hostIPC: false
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "configMap"
    - "downwardAPI"
    - "emptyDir"
    - "persistentVolumeClaim"
    - "secret"
    - "projected"
    - "hostPath"
  allowedHostPaths:
    - pathPrefix: /var/run/docker.sock
  allowedCapabilities:
    - "*"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: policy-vector
  namespace: graylog
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - 5policy-vector
    verbs:
      - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: policy-vector
  namespace: graylog
subjects:
  - kind: ServiceAccount
    namespace: graylog
    name: default
roleRef:
  kind: Role
  name: policy-vector
  apiGroup: rbac.authorization.k8s.io
