apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-logger
  labels:
    k8s-app: fluentd-logging
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      name: vector-logger
  template:
    metadata:
      labels:
        name: vector-logger
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: vector-monitoring
        image: timberio/vector:0.10.0-alpine
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlibdockersock
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: vector-config
          mountPath: /etc/vector/
        - name: vector-cert
          mountPath: /etc/certs/vector/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlibdockersock
        hostPath:
          path: /var/run/docker.sock
      - name: vector-config
        configMap:
          name: vector-config
      - name: vector-cert
        secret:
          secretName: vector-cert
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.toml: |
    [sources.in]
      type = "docker"

    [sinks.out]
      encoding.codec = "json"
      inputs = ["in"]
      
      type = "socket"
      mode = "tcp"
      address = "graylog3:5555"

      # TLS
      tls.ca_file = "/etc/certs/vector/server.cert"
      tls.crt_file = "/etc/certs/vector/client.cert"
      tls.enabled = true
      tls.key_file = "/etc/certs/vector/client.key"
      tls.verify_certificate = false
