# Source: vector-agent/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-agent
  labels:
    helm.sh/chart: vector-agent-0.16.1
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: vector-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-agent
  labels:
    helm.sh/chart: vector-agent-0.16.1
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
data:
  # We leave `vector.toml` file name available to let externally managed config
  # maps to provide it.
  managed.toml: |
    # Configuration for vector.
    # Docs: https://vector.dev/docs/

    data_dir = "/vector-data-dir"

    [api]
      enabled = false
      address = "0.0.0.0:8686"
      playground = true

    [log_schema]
      host_key = "host"
      message_key = "message"
      source_type_key = "source_type"
      timestamp_key = "timestamp"

    # Ingest logs from Kubernetes.
    [sources.kubernetes_logs]
      type = "kubernetes_logs"

    [sinks.out]
      encoding.codec = "json"
      inputs = ["kubernetes_logs"]

      type = "socket"
      mode = "tcp"
      address = "graylog4:5555"

      # TLS
      tls.ca_file = "/etc/certs/vector/server.cert"
      tls.crt_file = "/etc/certs/vector/client.cert"
      tls.enabled = true
      tls.key_file = "/etc/certs/vector/client.key"
      tls.verify_certificate = false
---
# Source: vector-agent/templates/rbac.yaml
# Permissions to use Kubernetes API.
# Requires that RBAC authorization is enabled.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-agent
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
---
# Source: vector-agent/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-agent
  labels:
    helm.sh/chart: vector-agent-0.16.1
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-agent
subjects:
  - kind: ServiceAccount
    name: vector-agent
    namespace: graylog
---
# Source: vector-agent/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-agent
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    helm.sh/chart: vector-agent-0.16.1
    app.kubernetes.io/name: vector-agent
    app.kubernetes.io/instance: vector
    app.kubernetes.io/version: "0.16.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vector-agent
      app.kubernetes.io/instance: vector
  minReadySeconds: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:

        checksum/config: 75958f6034a2d836d57468a572df3af05ea5d4eaf4b8b5cbd6371e6ec319a696

      labels:
        app.kubernetes.io/name: vector-agent
        app.kubernetes.io/instance: vector
        vector.dev/exclude: "true"
    spec:
      serviceAccountName: vector-agent
      securityContext:
        {}
      containers:
        - name: vector
          securityContext:
            {}
          image: "timberio/vector:0.16.1-debian"
          imagePullPolicy: "IfNotPresent"
          args:
            - --config
            - /etc/vector/*.toml
          env:
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VECTOR_SELF_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VECTOR_SELF_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            # Host log directory mount.
            - name: var-log
              mountPath: /var/log/
              readOnly: true
            # Host mount for docker and containerd log file symlinks.
            - name: var-lib
              mountPath: /var/lib
              readOnly: true
            # Vector data dir mount.
            - name: data-dir
              mountPath: "/vector-data-dir"
            # Vector config dir mount.
            - name: config-dir
              mountPath: /etc/vector
              readOnly: true
            # Vector certificates.
            - name: vector-cert
              mountPath: /etc/certs/vector/
              readOnly: true
      terminationGracePeriodSeconds: 60
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      volumes:
        # Log directory.
        - name: var-log
          hostPath:
            path: /var/log/
        # Docker and containerd log files in Kubernetes are symlinks to this folder.
        - name: var-lib
          hostPath:
            path: /var/lib/
        # Vector will store it's data here.
        - name: data-dir
          hostPath:
            path: /var/lib/vector/
        # Vector config dir.
        - name: config-dir
          projected:
            sources:
              - configMap:
                  name: vector-agent
        # Vector certificates.
        - name: vector-cert
          secret:
            secretName: vector-cert
