apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector-logger
  labels:
    k8s-app: fluentd-logging
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      name: vector-logger
  template:
    metadata:
      labels:
        name: vector-logger
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: vector-logger
      containers:
      - name: vector-monitoring
        image: timberio/vector:0.12.2-alpine
        env:
        - name: VECTOR_SELF_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: VECTOR_SELF_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: VECTOR_SELF_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: vector-config
          mountPath: /etc/vector/
        - name: vector-cert
          mountPath: /etc/certs/vector/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vector-config
        configMap:
          name: vector-config
      - name: vector-cert
        secret:
          secretName: vector-cert
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
data:
  vector.toml: |
    [sources.in]
      type = "kubernetes_logs"

    [sinks.out]
      encoding.codec = "json"
      inputs = ["in"]
      
      type = "socket"
      mode = "tcp"
      address = "graylog3:5555"

      # TLS
      tls.ca_file = "/etc/certs/vector/server.cert"
      tls.crt_file = "/etc/certs/vector/client.cert"
      tls.enabled = true
      tls.key_file = "/etc/certs/vector/client.key"
      tls.verify_certificate = false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector-logger
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector-logger
subjects:
  - kind: ServiceAccount
    name: vector-logger
    namespace: graylog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-logger
  namespace: graylog
