---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./moodle-cronjob.yaml
  - ./moodle-nginx.yaml
  - ./moodle-static.yaml
  - ./moodle.yaml
  - ./postgres.yaml
  - ./moodle4-cronjob.yaml
  - ./moodle4-static.yaml
  - ./moodle4-nginx.yaml
  - ./moodle4.yaml
  - ./postgres13.yaml
  - ./redis.yaml
  - ./ingress.yaml
  # - ./unavailable.yaml
  - ./secrets/moodle-config.yaml
  - ./secrets/moodle4-config.yaml
  - ./secrets/postgres.yaml
  - ./secrets/redis.yaml
namespace: moodle-ing
