---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: metabase
spec:
  description: Metabase database exploring service
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  destinations:
    - namespace: metabase
      server: https://146.83.63.70:6443
    - namespace: metabase
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "*"
    - group: "networking.k8s.io"
      kind: "*"
    - group: "bitnami.com"
      kind: SealedSecret
    - group: "batch"
      kind: "*"
    - group: ""
      kind: "Service"
    - group: ""
      kind: "Endpoints"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  destination:
    namespace: metabase
    server: "https://146.83.63.70:6443"
  source:
    path: metabase
    repoURL: "https://github.com/eol-uchile/argocd-config"
    targetRevision: main
  project: metabase
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase-oeol
  namespace: argocd
spec:
  destination:
    namespace: metabase
    server: 'https://kubernetes.default.svc'
  source:
    path: metabase
    repoURL: "https://github.com/eol-uchile/argocd-config"
    targetRevision: vastorga/migrate-metabase-oeol
  project: metabase
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
