apiVersion: v1
kind: Service
metadata:
  name: minio-exporter-eol
  namespace: monitoring
  labels:
    name: minio-exporter-eol
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9000
      targetPort: 27521
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-exporter-eol
  namespace: monitoring
subsets:
 - addresses:
   - ip: 146.83.63.76
   ports:
   - port: 27521
     name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-exporter-eol
  namespace: monitoring
  labels:
    name: minio-exporter-eol
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      name: minio-exporter-eol
  endpoints:
  - port: metrics
    path: /minio/v2/metrics/cluster
    interval: 30s