---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: graylog-backup-daily
spec:
  schedule: "0 7 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: graylog-backup
              image: old-backup-container
              args:
                - /root/scripts/backup.sh
                - daily
                - mongodb_graylog
              envFrom:
                - secretRef:
                    name: graylog
                - secretRef:
                    name: common
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: NotIn
                        values:
                          - k8seol0107
          tolerations:
            - key: "backups"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
