---
resources:
  - secrets/common.yaml
  - secrets/znuny.yaml
  - secrets/metabase.yaml
  - znuny.yaml
  - metabase.yaml
namespace: service-backup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: e7d191eeb61f0c10e93f50ec07f9a16defbb5b81
  - name: old-backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: b8f3899351938d6ae3a12cfd0700e3ce575308b8
