apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: metabase-backup-daily
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: metabase-backup
            image: backup-container
            args:
            - /root/scripts/backup.sh
            - daily
            - postgresql
            envFrom:
            - secretRef:
                name: metabase
            - secretRef:
                name: common
