apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: metabase-backup-daily
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: metabase-backup
            image: ghcr.io/eol-uchile/backup_container:d661d8e8bd88a21bb2479cdb65d4b807604db638
            args:
            - /root/scripts/backup_postgresql.sh
            envFrom:
            - secretRef:
                name: metabase
            - secretRef:
                name: common
