apiVersion: batch/v1
kind: CronJob
metadata:
  name: metabase-backup-daily
spec:
  schedule: "30 7 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: metabase-backup
            image: backup-container
            args:
            - /root/scripts/backup.sh
            - daily
            - postgresql
            envFrom:
            - secretRef:
                name: metabase
            - secretRef:
                name: common
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - k8seol0101
                    - k8seol0102
                    - k8seol0104
                    - k8seol0105
                    - k8seol0107
          tolerations:
          - key: "backups"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
