---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metabase-backup-daily
spec:
  schedule: "30 7 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: metabase-backup
              image: backup-container
              args:
                - /root/scripts/backup.sh
                - daily
                - postgresql
              envFrom:
                - secretRef:
                    name: metabase
                - secretRef:
                    name: common
          tolerations:
            - key: "backups"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
