apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: otrs-backup-daily
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: otrs-backup
            image: ghcr.io/eol-uchile/backup_container:a944a5c7a527f8c3e48b40b254b1885647159fd9
            args:
            - /root/scripts/backup_postgresql.sh
            envFrom:
            - secretRef:
                name: otrs
            - secretRef:
                name: common
                