---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: znuny-backup-daily
spec:
  schedule: "0 8 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: znuny-backup
              image: old-backup-container
              args:
                - /root/scripts/backup.sh
                - daily
                - postgresql
              envFrom:
                - secretRef:
                    name: znuny
                - secretRef:
                    name: common
          tolerations:
            - key: "backups"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
