apiVersion: v1
kind: Service
metadata:
  name: node-exporter-external
  namespace: monitoring
  labels:
    name: node-exporter-external
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9100
      targetPort: 9100
---
apiVersion: v1
kind: Endpoints
metadata:
  name: node-exporter-external
  namespace: monitoring
subsets:
 - addresses:
   - ip: 146.83.63.75
   - ip: 146.83.63.76
   ports:
   - port: 9100
     name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter-external
  namespace: monitoring
  labels:
    name: node-exporter-external
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      name: node-exporter-external
  endpoints:
  - port: metrics
    interval: 30s
