apiVersion: v1
kind: Service
metadata:
  name: elastic-exporter-staging
  namespace: monitoring
  labels:
    name: elastic-exporter-staging
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 9114
      targetPort: 27125
---
apiVersion: v1
kind: Endpoints
metadata:
  name: elastic-exporter-staging
  namespace: monitoring
subsets:
 - addresses:
   - ip: 146.83.63.75
   ports:
   - port: 27125
     name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elastic-exporter-staging
  namespace: monitoring
  labels:
    name: elastic-exporter-staging
    prometheus: kube-prometheus
spec:
  selector:
    matchLabels:
      name: elastic-exporter-staging
  endpoints:
  - port: metrics
    interval: 30s