---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./moodle4-dev-cronjob.yaml
  - ./moodle4-dev-nginx.yaml
  - ./moodle4-dev-static.yaml
  - ./moodle4-dev.yaml
  - ./postgres.yaml
  - ./redis.yaml
  - ./ingress.yaml
  # - ./unavailable.yaml
  - ./secrets/moodle4-dev-config.yaml
  - ./secrets/postgres.yaml
  - ./secrets/redis.yaml
namespace: moodle-ing
