---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: moodle-dev
  annotations:
    reloader.stakater.com/auto: "true"
  name: moodle-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle-dev
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: moodle-dev
    spec:
      containers:
        - image: ghcr.io/eol-uchile/moodle-vlabx-docker:8566546abee0d0bf606a56104d02c30f87c839ae
          name: moodle-docker
          volumeMounts:
            - mountPath: /var/www/html/config.php
              name: config
              subPath: moodle.php
            - mountPath: /tmp
              name: tmpfs
            - mountPath: /var/www/moodledata
              name: data
          securityContext:
            readOnlyRootFilesystem: false
      volumes:
        - name: tmpfs
          emptyDir: {}
        - name: config
          secret:
            secretName: moodle-dev-config
        - name: data
          persistentVolumeClaim:
            claimName: moodle-dev-volume
---
apiVersion: v1
kind: Service
metadata:
  name: moodle-dev
  labels:
    app: moodle-dev
spec:
  ports:
    - port: 9000
      protocol: TCP
  selector:
    app: moodle-dev
