apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-node-daily
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: edx-backup
            image: eol-backup-container
            args:
            - /root/scripts/clear_mount.sh
            envFrom:
            - secretRef:
                name: common-config
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 1Gi
                cpu: 750m
            volumeMounts:
              - name: node7-persistent
                mountPath: /host_mount
          volumes:
            - name: node7-persistent
              hostPath:
                path: /mnt/data
                type: Directory
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - k8seol0107
          tolerations:
          - key: "backups"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
