apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-node-daily
spec:
  schedule: "0 8 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: edx-backup
            image: eol-backup-container
            args:
            - /root/scripts/clear_mount.sh
            envFrom:
            - secretRef:
                name: common-config
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 1Gi
                cpu: 750m
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - k8seol0103
