apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eol-backup
spec:
  schedule: "30 0-4,8-23 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: edx-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: eol-backup
            image: eol-backup-container
            args:
            - /root/scripts/backup.sh
            - hourly
            - mongodb_comments,mongodb,mysql
            - .
            envFrom:
            - secretRef:
                name: common-config
            - secretRef:
                name: eol-config
            resources:
              requests:
                memory: 256Mi
                cpu: 750m
              limits:
                memory: 2Gi
                cpu: 750m
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - k8seol0101
                    - k8seol0102
                    - k8seol0103
                    - k8seol0104
                    - k8seol0105
          tolerations:
          - key: "backups"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          #  volumeMounts:
          #  - mountPath: /volume/nfs
          #    name: eol-backup
          #volumes:
          #- name: eol-backup
          #  nfs:
          #    server: 172.16.244.123
          #    path: /eol_backup/eol
          #   podAntiAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #     - labelSelector:
          #         matchExpressions:
          #         - key: app
          #           operator: In
          #           values:
          #           - edx-backup
          #       topologyKey: "kubernetes.io/hostname"
          # tolerations:
          # - key: "dev"
          #   operator: "Equal"
          #   value: "nosso"
          #   effect: "NoSchedule"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: eol-backup-daily
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: edx-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: eol-backup
            image: eol-backup-container
            args:
            - /root/scripts/backup.sh
            - daily
            - mongodb_comments,mongodb,mysql,minio
            - keep
            envFrom:
            - secretRef:
                name: common-config
            - secretRef:
                name: eol-config
            resources:
              requests:
                memory: 256Mi
                cpu: 750m
              limits:
                memory: 2Gi
                cpu: 750m
            volumeMounts:
              - name: node7-persistent
                mountPath: /host_mount
          volumes:
            - name: node7-persistent
              hostPath:
                path: /mnt/data
                type: Directory
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - k8seol0101
                    - k8seol0102
                    - k8seol0103
                    - k8seol0104
                    - k8seol0105
          tolerations:
          - key: "backups"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          # affinity:
          #   podAntiAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #     - labelSelector:
          #         matchExpressions:
          #         - key: app
          #           operator: In
          #           values:
          #           - edx-backup
          #       topologyKey: "kubernetes.io/hostname"
