apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
- secrets/eol.yaml
- psp.yaml
- eol.yml
- uabierta.yaml
- secrets/uabierta.yaml
- virtuallabx.yml
- secrets/virtuallabx.yaml
images:
- name: uabierta-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: f89f32c5ddd551cbed5c935ba4a2d47514a96e8e
- name: eol-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: f89f32c5ddd551cbed5c935ba4a2d47514a96e8e
- name: vlabx-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: old-f89f32c5ddd551cbed5c935ba4a2d47514a96e8e