apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
- secrets/common.yaml
- secrets/eol.yaml
- secrets/uabierta.yaml
- secrets/virtuallabx.yaml
- secrets/norteamericano.yaml
- secrets/openuchile.yaml
- psp.yaml
- eol.yaml
- uabierta.yaml
- virtuallabx.yaml
- norteamericano.yaml
- openuchile.yaml
- clean-node.yaml
images:
- name: uabierta-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 87e8048f3f4df73ac0e1216454dbc34ff30f14f8
- name: eol-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 09db741a8a2f43745514efcf0194f3966854cac3
- name: vlabx-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 87e8048f3f4df73ac0e1216454dbc34ff30f14f8
- name: norteamericano-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 87e8048f3f4df73ac0e1216454dbc34ff30f14f8
- name: openuchile-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 87e8048f3f4df73ac0e1216454dbc34ff30f14f8
