apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
- secrets/common.yaml
- secrets/eol.yaml
- secrets/uabierta.yaml
- secrets/virtuallabx.yaml
- psp.yaml
- eol.yml
- uabierta.yaml
- virtuallabx.yml
- clean-node.yml
images:
- name: uabierta-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 2a4e94e77aae7fee529eba517f2f11caa99c4e87
- name: eol-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 2a4e94e77aae7fee529eba517f2f11caa99c4e87
- name: vlabx-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: old-2a4e94e77aae7fee529eba517f2f11caa99c4e87
