resources:
- secrets/eol.yaml
- psp.yaml
- secrets/eduabierta.yaml
- eol.yml
- eduabierta.yaml
- uabierta.yaml
- secrets/uabierta.yaml

namespace: edx-backup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
