apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
- secrets/common.yaml
- secrets/eol.yaml
- secrets/uabierta.yaml
- secrets/virtuallabx.yaml
- secrets/norteamericano.yaml
- secrets/openuchile.yaml
- psp.yaml
- eol.yml
- uabierta.yaml
- virtuallabx.yml
- norteamericano.yml
- openuchile.yml
- clean-node.yml
images:
- name: uabierta-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 232f01fa23ed57c77b8909fc77cfe8a8c4096fa5
- name: eol-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 232f01fa23ed57c77b8909fc77cfe8a8c4096fa5
- name: vlabx-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 232f01fa23ed57c77b8909fc77cfe8a8c4096fa5
- name: norteamericano-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 232f01fa23ed57c77b8909fc77cfe8a8c4096fa5
- name: openuchile-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 232f01fa23ed57c77b8909fc77cfe8a8c4096fa5
