---
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
  - secrets/common.yaml
  - secrets/virtuallabx.yaml
  - virtuallabx.yaml
  - clean-node.yaml
images:
  - name: old-backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: b8f3899351938d6ae3a12cfd0700e3ce575308b8
