apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
- secrets/common.yaml
- secrets/eol.yaml
- secrets/uabierta.yaml
- secrets/virtuallabx.yaml
- psp.yaml
- eol.yml
- uabierta.yaml
- virtuallabx.yml
- clean-node.yml
images:
- name: uabierta-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 8437c2c906b05f8e28d59fc5c331565253ec9e14
- name: eol-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 8437c2c906b05f8e28d59fc5c331565253ec9e14
- name: vlabx-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: old-8437c2c906b05f8e28d59fc5c331565253ec9e14
