---
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
  - secrets/common.yaml
  - secrets/eol.yaml
  - secrets/virtuallabx.yaml
  - secrets/redfid.yaml
  - secrets/openuchile.yaml
  - eol.yaml
  - virtuallabx.yaml
  - redfid.yaml
  - openuchile.yaml
  - clean-node.yaml
images:
  - name: old-backup-container
    newName: ghcr.io/eol-uchile/backup_container
    newTag: 67c54592a99d983f2aca437a2583049c65e8d75d
