resources:
- secrets/eol.yaml
- psp.yaml
- eol.yml
- uabierta.yaml
- secrets/uabierta.yaml
- virtuallabx.yml
- secrets/virtuallabx.yaml

namespace: edx-backup
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
