apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
- secrets/common.yaml
- secrets/eol.yaml
- secrets/uabierta.yaml
- secrets/virtuallabx.yaml
- secrets/norteamericano.yaml
- secrets/openuchile.yaml
- psp.yaml
- eol.yaml
- uabierta.yaml
- virtuallabx.yaml
- norteamericano.yaml
- openuchile.yaml
- clean-node3.yaml
- clean-node5.yaml
images:
- name: uabierta-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: bfe0d5581f2e15605360e7d5f255d5ce65a5ad5d
- name: eol-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: bfe0d5581f2e15605360e7d5f255d5ce65a5ad5d
- name: vlabx-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: bfe0d5581f2e15605360e7d5f255d5ce65a5ad5d
- name: norteamericano-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: bfe0d5581f2e15605360e7d5f255d5ce65a5ad5d
- name: openuchile-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: bfe0d5581f2e15605360e7d5f255d5ce65a5ad5d
