apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
- secrets/eol.yaml
- psp.yaml
- eol.yml
- uabierta.yaml
- secrets/uabierta.yaml
- virtuallabx.yml
- secrets/virtuallabx.yaml
images:
- name: uabierta-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: cb3a3e1340f13f9a65696a0cdacc58e5c9e4400d
- name: eol-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: cb3a3e1340f13f9a65696a0cdacc58e5c9e4400d
- name: vlabx-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: old-cb3a3e1340f13f9a65696a0cdacc58e5c9e4400d