apiVersion: kustomize.config.k8s.io/v1beta1
namespace: edx-backup
kind: Kustomization
resources:
- secrets/common.yaml
- secrets/eol.yaml
- secrets/uabierta.yaml
- secrets/virtuallabx.yaml
- psp.yaml
- eol.yml
- uabierta.yaml
- virtuallabx.yml
- clean-node.yml
images:
- name: uabierta-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 5d3133a8fae528e250ab364ad65d75de67659efa
- name: eol-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: 5d3133a8fae528e250ab364ad65d75de67659efa
- name: vlabx-backup-container
  newName: ghcr.io/eol-uchile/backup_container
  newTag: old-5d3133a8fae528e250ab364ad65d75de67659efa