---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: 5policy-edx-backup
  namespace: edx-backup
spec:
  privileged: false
  hostNetwork: false
  hostPorts: []
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostPID: false
  hostIPC: false
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - secret
    - projected
    - nfs
  allowedCapabilities:
    - '*'
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: policy-edx-backup
  namespace: edx-backup
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - 5policy-edx-backup
    verbs:
      - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: policy-edx-backup
  namespace: edx-backup
subjects:
  - kind: ServiceAccount
    namespace: edx-backup
    name: default
roleRef:
  kind: Role
  name: policy-edx-backup
  apiGroup: rbac.authorization.k8s.io
