apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: uabierta-backup
spec:
  schedule: "0 0-5,7-23 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: uabierta-backup
            image: ghcr.io/eol-uchile/backup_container:50851d2a1ba3646fd598a22b483e56ed97333771
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 2Gi
                cpu: "1"
            args:
            - /root/scripts/backup.sh
            - hourly
            envFrom:
            - secretRef:
                name: uabierta-config
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - k8seol0101
                    - k8seol0102
          #  volumeMounts:
          #  - mountPath: /volume/nfs
          #    name: uabierta-backup
          #volumes:
          #- name: uabierta-backup
          #  nfs:
          #    server: 172.16.244.123
          #    path: /eol_backup/uabierta
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: uabierta-backup-daily
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: uabierta-backup
            image: ghcr.io/eol-uchile/backup_container:50851d2a1ba3646fd598a22b483e56ed97333771
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 2Gi
                cpu: "1"
            args:
            - /root/scripts/backup.sh
            - daily
            envFrom:
            - secretRef:
                name: uabierta-config
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - k8seol0101
                    - k8seol0102
          #  volumeMounts:
          #  - mountPath: /volume/nfs
          #    name: uabierta-backup
          #volumes:
          #- name: uabierta-backup
          #  nfs:
          #    server: 172.16.244.123
          #    path: /eol_backup/uabierta
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: uabierta-backup-minio-daily
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: uabierta-backup
            image: ghcr.io/eol-uchile/backup_container:50851d2a1ba3646fd598a22b483e56ed97333771
            resources:
              requests:
                memory: 256Mi
              limits:
                memory: 2Gi
                cpu: "1"
            args:
            - /root/scripts/backup_minio.sh
            envFrom:
            - secretRef:
                name: uabierta-config
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                    - k8seol0101
                    - k8seol0102
          #  volumeMounts:
          #  - mountPath: /volume/nfs
          #    name: uabierta-backup
          #volumes:
          #- name: uabierta-backup
          #  nfs:
          #    server: 172.16.244.123
          #    path: /eol_backup/uabierta
