apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: uabierta-backup
spec:
  schedule: "0 0-5,7-23 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: uabierta-backup
            image: ghcr.io/eol-uchile/backup_container:538fd1e9d8373e5e71c8cef9e96b4e6ec40f2df4
            args:
            - /root/scripts/backup_hourly.sh
            env:
            - name: BACKUP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: BACKUP_PASSWORD
            - name: PLATFORM_GDRIVE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_GDRIVE_CLIENT_SECRET
            - name: PLATFORM_GDRIVE_SCOPE
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_GDRIVE_SCOPE
            - name: PLATFORM_GDRIVE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_GDRIVE_TOKEN
            - name: PLATFORM_GRIVE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_GRIVE_CLIENT_ID
            - name: PLATFORM_MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MONGODB_HOST
            - name: PLATFORM_MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MONGODB_PORT
            - name: PLATFORM_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MONGODB_PASSWORD
            - name: PLATFORM_MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MONGODB_USER
            - name: PLATFORM_MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MYSQL_HOST
            - name: PLATFORM_MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MYSQL_PORT
            - name: PLATFORM_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MYSQL_PASSWORD
            - name: PLATFORM_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MYSQL_USER
            - name: PLATFORM_MYSQL_DATABASES
              valueFrom:
                secretKeyRef:
                  name: eol-config
                  key: PLATFORM_MYSQL_DATABASES
            - name: PLATFORM_NAME
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_NAME
            - name: PLATFORM_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_S3_ACCESS_KEY
            - name: PLATFORM_S3_BUCKETS
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_S3_BUCKETS
            - name: PLATFORM_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_S3_SECRET_KEY
            - name: PLATFORM_S3_URL
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_S3_URL
          #  volumeMounts:
          #  - mountPath: /volume/nfs
          #    name: uabierta-backup
          #volumes:
          #- name: uabierta-backup
          #  nfs:
          #    server: 172.16.244.123
          #    path: /eol_backup/uabierta
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: uabierta-backup-daily
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: uabierta-backup
            image: ghcr.io/eol-uchile/backup_container:538fd1e9d8373e5e71c8cef9e96b4e6ec40f2df4
            args:
            - /root/scripts/backup.sh
            env:
            - name: BACKUP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: BACKUP_PASSWORD
            - name: PLATFORM_GDRIVE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_GDRIVE_CLIENT_SECRET
            - name: PLATFORM_GDRIVE_SCOPE
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_GDRIVE_SCOPE
            - name: PLATFORM_GDRIVE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_GDRIVE_TOKEN
            - name: PLATFORM_GRIVE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_GRIVE_CLIENT_ID
            - name: PLATFORM_MONGODB_HOST
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MONGODB_HOST
            - name: PLATFORM_MONGODB_PORT
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MONGODB_PORT
            - name: PLATFORM_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MONGODB_PASSWORD
            - name: PLATFORM_MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MONGODB_USER
            - name: PLATFORM_MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MYSQL_HOST
            - name: PLATFORM_MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MYSQL_PORT
            - name: PLATFORM_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MYSQL_PASSWORD
            - name: PLATFORM_MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_MYSQL_USER
            - name: PLATFORM_MYSQL_DATABASES
              valueFrom:
                secretKeyRef:
                  name: eol-config
                  key: PLATFORM_MYSQL_DATABASES
            - name: PLATFORM_NAME
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_NAME
            - name: PLATFORM_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_S3_ACCESS_KEY
            - name: PLATFORM_S3_BUCKETS
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_S3_BUCKETS
            - name: PLATFORM_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_S3_SECRET_KEY
            - name: PLATFORM_S3_URL
              valueFrom:
                secretKeyRef:
                  name: uabierta-config
                  key: PLATFORM_S3_URL
          #  volumeMounts:
          #  - mountPath: /volume/nfs
          #    name: uabierta-backup
          #volumes:
          #- name: uabierta-backup
          #  nfs:
          #    server: 172.16.244.123
          #    path: /eol_backup/uabierta
