---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: basic-auth
spec:
  encryptedData:
    auth: AgBqaSjNADl0BOODNufmKgVNIYm+P3wb34rZCtKnFu9p3PdLcKNWFo6Yyw7XbRm22eP5a8BCmBbKMbvZ3GaNt6ktR6GmfwcEl4nYgrLg/xd7dH4n9K+ZyphkWxhT/zqliMea1P5imuv2F+cONFX9QCBWi0WSJwYVE4EyGuwJ1PcpWse62hBuHnMORwoa74zNkCsk5u7WVKh90VWOIRKEWNZcSmPVFyRgPhQ6HwS3By/P/n7GySKpjQ1C9aVrRA6XKMjCef+kp1/Xf7AmhE7cBU0vtfCFtvIoNt6K0IMshz6VnwRLzocPclVHn4JGhKnbmC3AUnpoQqO3INfcQI0kY3vsP7guCdZ6jdET790yYQt+sVdZqzwF4Lvjdh4Sb1EcMXXZ+eUrbs9GaaMBEiSE/AKd4kdlw7SVB91MHiqIUDZP3lIkdPWVJKU6lz+KkFfqymmXumcu5MW2uChVofinPI92RmUCG9rFa73QeGyZ82UFSu6Vv+WXguyTjNjIqshZ/fn9RCV0CaFw06x4s0ng5V+TzNMtEZHJ/vgnPtaWJDKhJ4H6PzsdD22JfjwKeaHDDSks5m3wCx8k/gk2NHABZa9leAVF+IDGopqm7LkNG8newBrljzEc36BuyLPWUkcUSmbJeJzoNwjussqp6RAmdGVXzqJ0qflf2uh6GDoiOIos43pujkcUNAm5yXzbs5Xa+1mhm+pTmPxRPAeKLZwE9ye5zQwa/4dNWQHEusMa0C1l2TMR7o4Wcj/q9XUagkuhxoGedJQIfZAJr10BFCbycYQHsg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: basic-auth
