apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: basic-auth
spec:
  encryptedData:
    auth: AgAkkXp/Tmv+3HBK2VqjQvKYXXpdm86DGJMP223pRkptoyONfuXR0SY+Gb7o4V7w/4V0w6DxU51Naszv6Obt7PqoOAg+XhbC2Ig9O7iCae8TXqr9I7fp9IUA1h5KQImbKKYegpdvnKCrFBudm40Y0Q1kQitaloOOZTWM6c4HL3hsGyLV+fsgXJgULDtviLwNbYd68jaeSIkRXsAW9FsTrCLX615A8ocG0EoKnfloA537NIoAqjjJjyLoQzhuM53E1NJXmjrwct2fVbkXnckyLbVeUaAwyh6lBmXmgmbIeswAiPb0ifRFlWib+WGcNv+lGFV0JJlorDMbwQUskAzHCpdvgIo1OXLaCXhHcO6wqVAVmK0KvofZscOkFtytd1a3bwgj0HsJOWtdmRq/AEoPs/M9eK74AJe9pkjx9ZPvJrGAb8xH5vvvzNw4R6JxqVxDv1bSzNDg1WJLb9iAe2hcB3lYv352wNVch58BsgJmtz+gGKm8lIwUG6MfyJVZjd5xffvZe86cHq63FE8RApahiNVhzlNKP/2Te8AVRbK1oh+do8lgd49Gh2piIAr9/xI802gA6DzSmrO77pBlneEzYho1dR8fXWs5kYHf22S9qMRIIlwCBerCewoC8XU7AqKrmqNs+Uta2zseqUN1oasFXmRfRtezCafOCQWkinomtC77CjCta2oMq6MNjk2VYQ+qUAZeiumnhkeMojb4MRpGhcpB+HvyvuH1pm1YJHNvZ17efo7NaiInB878Zz9aHIiZih7FgHbMx0qfKvCvDYWZx5XvOg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: basic-auth

