apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: reloader
  namespace: argocd
spec:
  description: Project to backup uabierta databases
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: reloader
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: 'ServiceAccount'
  - group: 'rbac.authorization.k8s.io'
    kind: 'ClusterRole'
  - group: 'rbac.authorization.k8s.io'
    kind: 'ClusterRoleBinding'
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: 'Deployment'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
spec:
  destination:
    namespace: reloader
    server: 'https://kubernetes.default.svc'
  source:
    path: reloader
    repoURL: 'https://github.com/fdns/argocd-config'
    targetRevision: HEAD
  project: reloader
