apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  description: Project to backup uabierta databases
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceWhitelist:
  - group: 'networking.k8s.io'
    kind: Ingress
  - group: 'bitnami.com'
    kind: SealedSecret
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd-ingress
    repoURL: 'https://github.com/fdns/argocd-config'
    targetRevision: HEAD
  project: argocd-ingress
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
