apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openuchile-services
  namespace: argocd
spec:
  description: Store generic services for openuchile cluster
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: 'https://146.83.63.78:6443'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openuchile-reloader
  namespace: argocd
spec:
  destination:
    namespace: reloader
    server: 'https://146.83.63.78:6443'
  source:
    path: reloader
    repoURL: 'https://github.com/eol-uchile/argocd-config'
    targetRevision: HEAD
  project: openuchile-services
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
