apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: openuchile-services
  namespace: argocd
spec:
  description: Store generic services for openuchile cluster
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: '*'
    server: 'https://146.83.63.78:6443'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: 'apps'
    kind: '*'
  - group: 'networking.k8s.io'
    kind: '*'
  - group: 'bitnami.com'
    kind: SealedSecret
  - group: 'batch'
    kind: '*'
  - group: ''
    kind: 'Service'
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: 'Endpoints'
  - group: 'autoscaling'
    kind: 'HorizontalPodAutoscaler'
  - group: ''
    kind: 'PersistentVolumeClaim'
  - group: 'monitoring.coreos.com'
    kind: Probe
