apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openuchile-reloader
  namespace: argocd
spec:
  destination:
    namespace: reloader
    server: 'https://146.83.63.78:6443'
  source:
    path: reloader
    repoURL: 'https://github.com/eol-uchile/argocd-config'
    targetRevision: HEAD
  project: openuchile-services
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
