---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: edx-sandbox
  namespace: argocd
spec:
  description: Project for applications in edx sandbox
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: edx-sandbox
      server: https://146.83.63.70:6443
    - namespace: edx-sandbox
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "apps"
      kind: "*"
    - group: "networking.k8s.io"
      kind: "*"
    - group: "bitnami.com"
      kind: SealedSecret
    - group: "batch"
      kind: "*"
    - group: ""
      kind: "Service"
    - group: ""
      kind: "Endpoints"
    - group: "discovery.k8s.io"
      kind: "EndpointSlice"
    - group: "autoscaling"
      kind: "HorizontalPodAutoscaler"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edx-sandbox
  namespace: argocd
spec:
  destination:
    namespace: edx-sandbox
    server: "https://146.83.63.70:6443"
  source:
    path: sandbox
    repoURL: "https://github.com/eol-uchile/edx-kustomize"
    targetRevision: HEAD
  project: edx-sandbox
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edx-sandbox-oeol
  namespace: argocd
spec:
  destination:
    namespace: edx-sandbox
    server: "https://kubernetes.default.svc"
  source:
    path: sandbox
    repoURL: "https://github.com/eol-uchile/edx-kustomize"
    targetRevision: vastorga/add-sandbox-oeol
  project: edx-sandbox
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
