name: Check kustomize integrity

on:
  push:
    paths-ignore:
      - '.github/workflows/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2.1.0
        with:
          kustomize-version: 5.6.0

      - name: Check backup build
        run: |
          kustomize build edx-backup > /dev/null

      - name: Check graylog build
        run: |
          kustomize build graylog > /dev/null

      - name: Check reloader build
        run: |
          kustomize build reloader > /dev/null

      - name: Check service-backup build
        run: |
          kustomize build service-backup > /dev/null

      - name: Check projects build
        run: |
          kustomize build projects > /dev/null
