name: Check kustomize integrity

on:
  push:
    paths-ignore:
      - '.github/workflows/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2.1.0
        with:
          kustomize-version: 5.7.0

      - name: Check backup build
        run: |
          kustomize build edx-backup > /dev/null

      - name: Check graylog build
        run: |
          kustomize build graylog > /dev/null

      - name: Check metabase build
        run: |
          kustomize build metabase > /dev/null

      - name: Check monitoring build
        run: |
          kustomize build monitoring > /dev/null

      - name: Check znuny build
        run: |
          kustomize build znuny > /dev/null

      - name: Check reloader build
        run: |
          kustomize build reloader > /dev/null

      - name: Check service-backup build
        run: |
          kustomize build service-backup > /dev/null

      - name: Check portal-eol build
        run: |
          kustomize build portal-eol > /dev/null

      - name: Check docs-eol build
        run: |
          kustomize build docs-eol > /dev/null

      - name: Check test-host-eol build
        run: |
          kustomize build test-host-eol > /dev/null

      - name: Check projects build
        run: |
          kustomize build projects > /dev/null

      - name: Check emi-project build
        run: |
          kustomize build emi-project > /dev/null

      - name: Check moodle-virtuallabx build
        run: |
          kustomize build moodle-virtuallabx > /dev/null

      - name: Check moodle-vlabx-backup build
        run: |
          kustomize build moodle-vlabx-backup > /dev/null
