name: Update docs-eol version

on:
  repository_dispatch:
    types: [update-docs]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install kustomize
        run: cd /tmp && curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && sudo install -m 755 kustomize /usr/local/bin/kustomize && cd

      - name: Update docs-eol version
        run: |
          cd docs-eol
          NEWVERSION=$(curl https://api.github.com/repos/eol-uchile/docs-eol/commits/main | jq -r '.sha')
          kustomize edit set image docs=ghcr.io/eol-uchile/docs-eol:$NEWVERSION
          cd ..

      - name: Push changes
        run: |
          if [ "$(git status --porcelain portal-eol/)" != "" ]
          then
            git config --global user.name ${{ github.actor }}
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git add docs-eol/kustomization.yaml
            git commit -m "Update docs-eol version"
            git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/eol-uchile/argocd-config.git HEAD:master
          else
            echo "No changes to commit. Skipping commit step."
          fi
