name: Update docs-eol version

on:
  repository_dispatch:
    types: [update-docs]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install kustomize
        uses: imranismail/setup-kustomize@v2.1.0
        with:
          kustomize-version: 5.7.0

      - name: Update docs-eol version
        run: |
          cd docs-eol
          NEWVERSION=$(gh api --header "Accept: application/vnd.github+json" --header "X-GitHub-Api-Version: 2022-11-28" /orgs/eol-uchile/packages/container/docs-eol/versions | jq '.[0] | .metadata.container.tags[]' | sed 's#"##g')
          kustomize edit set image docs=ghcr.io/eol-uchile/docs-eol:$NEWVERSION
          cd ..

      - name: Push changes
        run: |
          if [ "$(git status --porcelain docs-eol/)" != "" ]
          then
            git config --global user.name ${{ github.actor }}
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git add docs-eol/kustomization.yaml
            git commit -m "Update docs-eol version"
            git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/eol-uchile/argocd-config.git HEAD:main
          else
            echo "No changes to commit. Skipping commit step."
          fi
