name: Update portal-eol version

on:
  repository_dispatch:
    types: [update-portal]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && sudo install -m 755 kustomize /usr/local/bin/kustomize

      - name: Update portal-eol version
        run: |
          cd portal-eol
          NEWVERSION=$(curl https://api.github.com/repos/eol-uchile/portal-eol/commits/master | jq -r '.sha')
          kustomize edit set image portal=ghcr.io/eol-uchile/portal-eol:$NEWVERSION
          cd ..

      - name: Push changes
        run: |
          git config --global user.name ${{ github.actor }}
          git add portal-eol/kustomization.yaml
          git commit -m "Update portal-eol version"
          git push https://eolito:${{ secrets.GITHUB_TOKEN }}@github.com/eol-uchile/argocd-config.git HEAD:master
