name: Update docs-eol version

on:
  repository_dispatch:
    types: [update-docs]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install kustomize
        run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && sudo install -m 755 kustomize /usr/local/bin/kustomize

      - name: Update docs-eol version
        run: |
          cd docs-eol
          NEWVERSION=$(curl https://api.github.com/repos/eol-uchile/docs-eol/commits/master | jq -r '.sha')
          kustomize edit set image docs=ghcr.io/eol-uchile/docs-eol:$NEWVERSION
          cd ..

      - name: Push changes
        run: |
          git config --global user.name "eolito"
          git config --global user.email 'eol-uchile@users.noreply.github.com'
          git add docs-eol/kustomization.yaml
          git commit -m "Update docs-eol version"
          git push https://eolito:${{ secrets.GITHUB_TOKEN }}@github.com/eol-uchile/argocd-config.git HEAD:master
