name: Update docs-eol version

on:
  repository_dispatch:
    types: [update-docs]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install kustomize
        run: cd /tmp && curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash && sudo install -m 755 kustomize /usr/local/bin/kustomize && cd

      - name: Update docs-eol version
        run: |
          cd docs-eol
          NEWVERSION=$(gh api --header "Accept: application/vnd.github+json" --header "X-GitHub-Api-Version: 2022-11-28" /orgs/eol-uchile/packages/container/docs-eol/versions | jq '.[0] | .metadata.container.tags[]' | sed 's#"##g')
          kustomize edit set image docs=ghcr.io/eol-uchile/docs-eol:$NEWVERSION
          cd ..

      - name: Push changes
        run: |
          if [ "$(git status --porcelain docs-eol/)" != "" ]
          then
            git config --global user.name ${{ github.actor }}
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"
            git add docs-eol/kustomization.yaml
            git commit -m "Update docs-eol version"
            git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/eol-uchile/argocd-config.git HEAD:master
          else
            echo "No changes to commit. Skipping commit step."
          fi
