apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v0.16.1
    chart: cert-manager
  project: cert-manager
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
